# Generated by Django 5.2.6 on 2025-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=50)),
                ("company_location", models.CharField(max_length=50)),
                ("company_about", models.TextField()),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Non IT", "Non IT"),
                            ("Mobiles Phones", "Mobile Phones"),
                            ("BA", "BA"),
                        ],
                        max_length=100,
                    ),
                ),
                ("added_data", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
